import { DISH_LOOKUP } from '../lib/data/messDishes';

const needed_ids = [
    "dish_multigrain_dosa", "dish_pav_bhaji", "dish_coconut_chutney", "dish_mint_chutney", "dish_bread_butter", "dish_sprouts_cup", "dish_mess_chai",
    "dish_scrambled_egg", "dish_boiled_eggs", "dish_masala_onion_omelet", "dish_egg_bhurji",
    "dish_boiled_soya_bean_salad", "dish_boiled_peanut_sundal", "dish_boiled_paneer_salad", "dish_boiled_chickpeas_salad", "dish_paneer_bhurji", "dish_ragi_malt", "dish_greek_yogurt_salad", "dish_sweet_potato_salad",
    "dish_medu_vada", "dish_moong_dal_palak_thepla", "dish_mess_sambar", "dish_tomato_chutney", "dish_peanut_chutney",
    "dish_poori_serving", "dish_lemon_sevai", "dish_aloo_mutter_curry",
    "dish_uggani_mirchi_bajji", "dish_methi_roti_pair", "dish_green_peas_tomato_sabji",
    "dish_onion_carrot_uttapam", "dish_vegetable_poha",
    "dish_shavige_bath", "dish_paneer_paratha_pair", "dish_mess_curd",
    "dish_carrot_idli", "dish_bhature_pair", "dish_chana_masala",
    "dish_onion_dosa", "dish_vada_pav",
    "dish_onion_rava_bonda", "dish_cucumber_poha",
    "dish_tomato_suji_upma", "dish_aloo_basin_chutney",
    "dish_pudina_chapathi_pair", "dish_dal_chutney",
    "dish_masala_ghee_roast_dosa", "dish_veg_moong_dal_khichdi",
    "dish_coconut_sevai", "dish_aloo_paratha", "dish_onion_tomato_chutney",
    "dish_konaseema_pottikkalu",
    "dish_carrot_cucumber_salad", "dish_tawa_roti_pair", "dish_steamed_rice", "dish_amaranthus_dal", "dish_beetroot_tomato_rasam", "dish_bisbele_bath", "dish_kakarakaya_fry", "dish_rajma_masala", "dish_mess_fryums_papad", "dish_dahi_vada", "dish_dosakaya_chutney", "dish_ghee_podi",
    "dish_onions_lemon_salad", "dish_palak_roti", "dish_gongura_dal", "dish_vegetable_dum_pulao", "dish_andhra_chicken_fry", "dish_masala_fish_fry", "dish_kaju_tomato_paneer", "dish_kala_chana_masala", "dish_butter_milk", "dish_coriander_tomato_chutney", "dish_gulab_jamun",
    "dish_ridge_gourd_dal", "dish_pudina_rice", "dish_guthi_vankaya_curry", "dish_cluster_beans_masala", "dish_lemon_sabja_water", "dish_potlakaya_perugu_chutney",
    "dish_beetroot_cucumber_salad", "dish_toor_dal_tadka", "dish_mess_rasam", "dish_jeera_rice", "dish_raw_banana_fry", "dish_aloo_gobi", "dish_sweet_lassi", "dish_beerakaya_chutney", "dish_semiya_payasam",
    "dish_mudda_pappu", "dish_pulihora", "dish_dondakaya_stir_fry", "dish_chole_soya_curry", "dish_majiga_pulusu", "dish_mess_pickle",
    "dish_moong_dal_fry", "dish_chicken_dum_biryani", "dish_paneer_dum_biryani", "dish_mirchi_ka_salan", "dish_onion_raita", "dish_nannari_sharbath", "dish_gongura_chutney", "dish_vanilla_ice_cream", "dish_chicken_thick_gravy",
    "dish_palak_dal", "dish_tomato_rice", "dish_pesara_punugulu_curry", "dish_drumstick_tomato_masala", "dish_jilebi",
    "dish_pachi_pulusu", "dish_special_rice", "dish_stir_fry_chicken_masala", "dish_stir_fry_paneer_masala", "dish_vegetable_jalfrezi", "dish_badusha",
    "dish_lobia_masala", "dish_poornalu",
    "dish_cauliflower_fry",
    "dish_kulfi",
    "dish_andhra_potato_fry", "dish_sweet_boondi",
    "dish_samosa", "dish_tomato_sauce", "dish_corn_vada", "dish_poha_cutlet", "dish_raw_banana_bajji", "dish_punugulu", "dish_dahi_puri", "dish_dry_maggi", "dish_kachori", "dish_onion_soft_pakoda", "dish_sambar_vada", "dish_mysore_bonda", "dish_pani_puri", "dish_sweet_corn_masala",
    "dish_beetroot_carrot_salad", "dish_dal_makhani", "dish_mushroom_biryani", "dish_snake_gourd_poriyal", "dish_guava_fruit", "dish_hot_milk_coffee",
    "dish_tomato_dal", "dish_sooji_upma_dinner", "dish_carrot_beans_poriyal", "dish_soya_chunks_curry", "dish_fruit_custard",
    "dish_dal_maharani", "dish_veg_manchuria_noodles", "dish_arbi_gravy", "dish_fresh_banana",
    "dish_lacha_paratha", "dish_pesara_pappu", "dish_chicken_curry", "dish_paneer_butter_masala", "dish_tomato_peas_capsicum", "dish_fresh_cut_fruits",
    "dish_mango_dal", "dish_bachali_kura_pulusu", "dish_set_dosa", "dish_cabbage_beans_poriyal", "dish_tomato_baingan_masala",
    "dish_ragi_dosa", "dish_vegetable_kurma",
    "dish_bhagara_rice", "dish_telangana_chicken_curry", "dish_achari_paneer", "dish_bhindi_masala",
    "dish_broken_wheat_upma",
    "dish_gobhi_manchuria_noodles",
    "dish_missi_roti", "dish_kadai_chicken", "dish_kadai_paneer",
    "dish_podi_onion_dosa",
    "dish_ragi_rava_upma", "dish_vegetable_kolhapuri",
    "dish_chettinad_chicken_curry", "dish_paneer_pepper_fry",
    "dish_chicken_65", "dish_paneer_65", "dish_chilli_chicken", "dish_chilli_paneer",
    "dish_pomegranate_juice", "dish_pineapple_juice", "dish_orange_juice", "dish_papaya_juice", "dish_grapes_juice", "dish_banana_milkshake", "dish_cold_badam_milk",
    "dish_museli_milk", "dish_chocos_milk", "dish_cornflakes_milk", "dish_brown_bread_peanut_butter",
    "dish_rasamalai", "dish_kalakand", "dish_carrot_halwa", "dish_puran_poli", "dish_motichoor_laddu", "dish_eggless_chocolate_cake",
    "dish_broccoli_soup", "dish_tomato_crouton_soup", "dish_creamy_mushroom_soup", "dish_mix_veg_ragi_soup", "dish_red_lentil_soup", "dish_lemon_coriander_soup", "dish_sweet_corn_soup", "dish_veg_manchow_soup"
];

console.log("Total DISH_LOOKUP size:", DISH_LOOKUP.size);
const missingInLookup = needed_ids.filter((id) => !DISH_LOOKUP.has(id));
console.log("Missing in DISH_LOOKUP:", missingInLookup.length, missingInLookup);
